### ISSUE TITLE
Query parameters currently must be passed in alphabetical order

### ISSUE THREAD

**Issue by lucasweb78** [lucasweb78/aws-v4-signer-java#2]
The AWS Canonical Request requires the query parameters to be sorted as per below: 

> Sort the parameter names by character code in ascending order (ASCII order)

Currently the signer does not do this and relies on them being passed in, in the correct order. The signer should be enhanced to handle query parameters in an order and to sort them correctly.

**Comment by yrodiere** [comment]
This is addressed in #4.
