### ISSUE TITLE
Content SHA256

### ISSUE THREAD

**Issue by YoSev** [lucasweb78/aws-v4-signer-java#5]
Hey there,

i am using your signer to create a signature to pass it to a javascript multipart/chunk uploader and i am wondering, if it is possible not to set the content-sha256, otherwise i would need to calculate it on the client site for every chunk and pass it to the server.

thanks

**Comment by lucasweb78** [comment]
The `content-sha256` is the sha-256 of the request's body, which in your case is chuck you are uploading. This is a required value when calculating the AWS V4 Signature as it is part of Canonical Request that needs to be included when signing the request. For more information see http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

**Comment by lucasweb78** [comment]
It actually looks there is an option with S3 to not include the `content-sha256` by setting the header `x-amz-content-sha256:UNSIGNED-PAYLOAD`, although this is not recommended by AWS as it is not as secure.

I'll re-open this issue and look at including support for this (see #7)

**Comment by adhamale2810** [comment]
@lucasweb78 hey, in my usecase i need to calculate the content-sha-256 i have tried using UNSIGNED-PAYLOAD but that doesn't work. Can u pls give some head on for how to calculate content-sha-256 i did try to make one implementation but still getting the error of content-sha256 mismatch.
`public static String getS3FileHash(InputStream inputStream) throws IOException, NoSuchAlgorithmException {
        MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
        DigestInputStream digestInputStream = new DigestInputStream(inputStream, messageDigest);
        byte[] buffer = new byte[8192];
        int count;
        while ((count = digestInputStream.read(buffer)) > -1) {
            // Update the digest with the data read from the stream
            messageDigest.update(buffer, 0, count);
        }
        byte[] remainingBytes = messageDigest.digest();
        StringBuilder sb = new StringBuilder();
        for (byte b : remainingBytes) {
            sb.append(String.format("%02x", b));
        }
        LOG.debug("ATHARVA: Hash of the file is: " + sb.toString());
        inputStream.close();
        return sb.toString();
    }
    `
This is what I hv tried but that doesn't work.

    
    Error:
    
   `
   <Error>
<Code>XAmzContentSHA256Mismatch</Code>
<Message>The provided 'x-amz-content-sha256' header does not match what was computed.</Message>
<ClientComputedContentSHA256>b562b79d19fc8004fe668f110249cffaf0cb685fe1f8413631aad858edd5b107</ClientComputedContentSHA256>
<S3ComputedContentSHA256>799e286c8361ae0df1c410b57f6e6e7492b816388aedcdd66532abacc68abd46</S3ComputedContentSHA256>
<RequestId>*******</RequestId>
<HostId>*******</HostId>
</Error>`
